# 1. Diz ao CloudCannon onde estão os dados dos projetos
data_config:
  projects:
    path: projects.json

# 2. Força o ficheiro index.html a abrir sempre no modo Visual
collections_config:
  pages:
    path: .
    glob: ['index.html']
    output: true

# 3. Define o editor visual como padrão para evitar erros
default_editor: visual
